Burger menu
js-tasks-ru/htmlcss-20230124_natalinebo2014 pull request #21
Opened 2023-02-23 14:46 UTC by NataliItaly

2023-02-23 14:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-23 16:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-23 22:35 UTC, GSemikozov requested changes

2023-02-23 22:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <input type="checkbox" class="burger__checkbox" name="burger-checkbox" id="burger-checkbox">
элементы бургер-меню болтаются вне блока - ошибка, так делать нельзя.

2023-02-23 22:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <nav class="header__nav" id="burger-menu">
это бургер-меню? id точно путает и не дает ясности где же на самом деле начинается блок .burger-menu )

2023-02-23 22:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.header__nav[data-open] {
описываем элемент хедера в блока .burger-menu? так нельзя) видимо, предпологалась какая-то специфическая логика меню, просто по классам надо правильно оформить

2023-02-23 23:37 UTC, NataliItaly commented on 09-lection7/01-burger-menu/burger-menu.css
> +.header__nav[data-open] {
поправила

2023-02-23 23:38 UTC, NataliItaly commented on 09-lection7/01-burger-menu/index.html
> +        <nav class="header__nav" id="burger-menu">
поправила

2023-02-23 23:38 UTC, NataliItaly commented on 09-lection7/01-burger-menu/index.html
> +        <input type="checkbox" class="burger__checkbox" name="burger-checkbox" id="burger-checkbox">
поправила

2023-02-23 23:42 UTC, NataliItaly commented on 09-lection7/01-burger-menu/index.html
> +        <input type="checkbox" class="burger__checkbox" name="burger-checkbox" id="burger-checkbox">
элементы бюргера были вне блока, так как хотела изначально открывать/закрывать меню на чистом css, а то потом до навигации из другого блока не достучишься

2023-02-23 23:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-24 00:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-24 18:24 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <input type="checkbox" class="burger__checkbox" name="burger-checkbox" id="burger-checkbox">
все равно нужно делать в рамках одного блока - просто тогда пришлось бы триггер включать в сам блок)

2023-02-24 18:29 UTC, GSemikozov requested changes

2023-02-24 18:29 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    position: absolute;
а почему бургер по умолчанию позиционируем абсолютом? должен идти в общем потоке, даже если интегрируем сразу в хедер - просто внутри кнопку-триггер можно делать как угодно, но - относительно самого блока

2023-02-24 22:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-24 22:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-24 23:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-25 00:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-27 12:41 UTC, GSemikozov requested changes

2023-02-27 12:41 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    display: none;
position: relative (чтобы .burger__checkbox позиционировался относительно того блока, которому принадлежит)

2023-02-27 12:41 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <div class="burger">
а где собственно меню которое открываем?) из разметки неясно

2023-02-27 12:41 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <div class="burger">
меню должно быть частью блока (например .burger__menu / .burger__window), и совершенно точно - не элементом другого блока (насколько я понимаю речь о header-nav)

2023-03-03 08:09 UTC, NataliItaly commented on 09-lection7/01-burger-menu/index.html
> +        <div class="burger">
Вот здесь не понятно. У меня в хедере лежит бургер, логотип и навигация. При клике на бургер открывается навигация. Разве бургер должен быть частью навигации? Тем более, что навигация на меньших экранах всегда будет скрыта за экраном и выезжать по клику на бургер. А бургер всегда виден и спозиционирован относительно хедера.

2023-03-03 16:02 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <div class="burger">
нет, в хедере лежит кнопка по нажатию на которую мы вызываем меню, и эта кнопка может быть абсолютно любой, но главное  - что она НЕ часть блока burger-menu

2023-03-06 00:23 UTC, NataliItaly commented on 09-lection7/01-burger-menu/index.html
> +        <div class="burger">
сделала две разных кнопки на открытие и закрытие меню.  кнопка закрытия находится в самом меню header__nav.
все таки непонятно: почему задание было сделать две разные кнопки? это лишает возможности прикрутить простейшую анимация для кнопки и в разметке появляется лишний элемент.

2023-03-06 09:17 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <div class="burger">
можно сделать одну общую как и было, главное - чтобы все элементы блока находились внутри блока, чтобы мы не залазили во внутреннюю реализацию одних блоков из других, в этом смысл

2023-03-06 09:22 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <div class="burger">
и по коду вижу что у нас опять 25: `<nav class="header__nav" id="header-nav">`...

1. кнопка вызова меню `<button>` - часть хедера
```
<button id="burger-menu-open">Open</button>
```
2. меню - независимый переиспользуемый блок, который можно показывать при нажатии на любую кнопку на которую повесим нужный обработчик события, в данном случае - на кнопку в хедере:
```
.burger {}
.burger__menu {}
.burger__menu {}
<div class="burger" id="burger-menu">
    <button class="burger__close" id="burger-menu-close">Close</button>
    <div class="burger__content">
        <nav class="burger__menu"></nav>
    </div>
</div>
```

2023-03-10 17:10 UTC, GSemikozov requested changes

2023-03-10 17:10 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger[data-open] {
не стоит разбивать описание блока на 2 части - 1 по умолчанию и 1 - в медиа-запросе, это все-таки один блок с одинаковыми стилями, через медиа-запрос надо только прятать на планшетах и десктопах

2023-03-10 17:10 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +        left: -100%;
на лекциях обсуждали, что такой способ - не очень хороший, есть лучше)

2023-03-12 22:28 UTC, NataliItaly commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger[data-open] {
исправила

2023-03-12 22:28 UTC, NataliItaly commented on 09-lection7/01-burger-menu/burger-menu.css
> +        left: -100%;
исправила на transform свойство

2023-03-17 16:33 UTC, GSemikozov approved these changes

2023-03-17 16:33 UTC, merged